"""What a printed byte looks like: code pages, bitmap glyphs and the text dump character.

Glyphs come from the open-licensed Spleen and X.Org misc-fixed bitmap fonts (tables in `fonts/`,
generated by scripts/generate_glyphs.py). Shapes approximate the printer's ROM fonts; the cell sizes
come from the device profile, so geometry is exact (design D5).

Bytes are drawn one cell each, in the order they arrive. Like the printers it simulates, emupos
never reorders them and never joins characters: a POS shapes and reverses Arabic before sending it.
"""

import codecs
from dataclasses import dataclass
from functools import cache, lru_cache
from importlib import resources
from typing import Literal

from PIL import Image, ImageChops, ImageDraw

from emupos.printer.escpos.render import scale

type FontName = Literal["A", "B"]

# Code pages with a glyph table for bytes 0x80-0xff: those listed in scripts/generate_glyphs.py.
GLYPH_CODE_PAGES = frozenset(
    {
        "PC437",
        "PC850",
        "PC852",
        "PC858",
        "PC860",
        "PC863",
        "PC865",
        "PC866",
        "WPC1252",
        "PC720",
        "PC864",
        "WPC1256",
    }
)

_GLYPH_FILES: dict[FontName, tuple[str, int]] = {
    "A": ("font-a-12x24.hex", 12),
    "B": ("font-b-9x17.hex", 9),
}


@dataclass(frozen=True, slots=True)
class Style:
    """Print modes that change how a character cell is drawn."""

    width: int = 1  # GS ! width multiplier
    height: int = 1  # GS ! height multiplier
    emphasized: bool = False  # ESC E, ESC G
    underline: int = 0  # ESC -: underline thickness in dots
    reverse: bool = False  # GS B: white on black


def python_codec(code_page: str) -> str | None:
    """The Python codec for a profile code-page name, e.g. PC864 -> cp864, WPC1256 -> cp1256."""
    name = code_page.lower().removeprefix("w").replace("pc", "cp", 1)
    try:
        return codecs.lookup(name).name
    except LookupError:
        return None


def dump_character(byte: int, code_page: str | None) -> str:
    """The character a byte adds to the text dump; U+FFFD when the code page has no mapping."""
    if byte < 0x80:
        return chr(byte)
    codec = python_codec(code_page) if code_page else None
    if codec is None:
        return "�"
    return bytes([byte]).decode(codec, errors="replace")


def glyph_character(byte: int, code_page: str | None) -> str | None:
    """The character whose glyph prints for a byte, or None to print the placeholder."""
    if byte < 0x80:
        return chr(byte)
    if code_page not in GLYPH_CODE_PAGES:
        return None
    return dump_character(byte, code_page)


@lru_cache(maxsize=4096)
def cell_image(
    font: FontName, cell: tuple[int, int], character: str | None, style: Style
) -> Image.Image:
    """One character cell of `cell` (width, height) dots in mode "1" (0 = ink), then scaled."""
    width, height = cell
    image = Image.new("1", (width, height), 255)
    bitmap = _glyph_table(font).get(ord(character)) if character else None
    if bitmap is None:
        _draw_placeholder(image)
    else:
        image.paste(_glyph_image(font, bitmap), (0, 0))
    if style.emphasized:  # strokes one dot wider: the glyph over itself shifted right
        shifted = Image.new("1", (width, height), 255)
        shifted.paste(image.crop((0, 0, width - 1, height)), (1, 0))
        image = ImageChops.logical_and(image, shifted)
    image = scale(image, style.width, style.height)
    if style.underline:
        ImageDraw.Draw(image).rectangle(
            (0, image.height - style.underline, image.width - 1, image.height - 1), fill=0
        )
    if style.reverse:
        image = ImageChops.invert(image)
    return image


def _draw_placeholder(image: Image.Image) -> None:
    """A box with a diagonal, filling the cell: clearly not a real character."""
    draw = ImageDraw.Draw(image)
    right, bottom = image.width - 2, image.height - 2
    draw.rectangle((1, 1, right, bottom), outline=0)
    draw.line((1, bottom, right, 1), fill=0)


def _glyph_image(font: FontName, bitmap: bytes) -> Image.Image:
    table_width = _GLYPH_FILES[font][1]
    rows = len(bitmap) // ((table_width + 7) // 8)
    return Image.frombytes("1", (table_width, rows), bitmap, "raw", "1;I")


@cache
def _glyph_table(font: FontName) -> dict[int, bytes]:
    file_name = _GLYPH_FILES[font][0]
    text = resources.files("emupos.printer.escpos").joinpath("fonts", file_name).read_text()
    table: dict[int, bytes] = {}
    for line in text.splitlines():
        if line and not line.startswith("#"):
            code_point, rows = line.split()
            table[int(code_point, 16)] = bytes.fromhex(rows)
    return table
